version: '3'
services:
  memgraph:
    image: memgraph/memgraph
    ports:
      - "7687:7687"
    command: ["--log-level=TRACE"]
  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687
  
  sng_demo:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    environment:
      MG_HOST: memgraph
      MG_PORT: 7687
    depends_on:
      - memgraph